### ISSUE TITLE
Battery_mon picking up all batteries, no label

### ISSUE THREAD

**Issue by Kenny-Dave** [smurphos/nemo_actions_and_cinnamon_scripts#24]
battery_mon is picking up the low battery on my mouse. Which is fine, but the message box is very confusing: 

![8IigRR6](https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/assets/44928929/dcc04528-d5bb-4d31-ba0b-1a6d07ed37c0)

It's obvs not going to hibernate if the mouse runs out of juice. We could do with a label as to what battery is running low. Thank you if you can adjust, I had a look but it is beyond me.

This is the system info text for the above: 

```
Battery:

  ID-1: hidpp_battery_0 charge: 18% condition: N/A volts: 3.7 min: N/A

    model: Logitech G903 LIGHTSPEED Wireless Gaming Mouse w/ HERO type: N/A serial: <filter>

    status: Discharging
```
